server:
  port: 16443
  error:
    include-stacktrace: on_param
  ssl:
    protocol: TLS
    enabled-protocols: TLSv1.3
    bundle: eudi-wallet

spring:
  ssl:
    bundle:
      pem:
        eudi-wallet:
          key:
            alias: eudi-wallet.localhost
          keystore:
            certificate: classpath:eudi-wallet.localhost.crt
            private-key: classpath:eudi-wallet.localhost.key
          truststore:
            certificate: classpath:eudi-ca.localhost.crt
        eudi-wallet-provider:
          key:
            alias: eudi-wallet-provider.localhost
          keystore:
            certificate: classpath:eudi-wallet-provider.localhost.crt
            private-key: classpath:eudi-wallet-provider.localhost.key
  application:
    name: eudi-wallet-mock
  datasource:
    url: jdbc:h2:mem:eudi-wallet
    driver-class-name: org.h2.Driver
    username: sa
    password:
  main:
    banner-mode: off

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true
